import type { Card } from "./types";

export const SAMPLE_CARDS: Card[] = [
  { id: "c1",  col: "ideas", title: "10 habitudes des créateurs ultra-productifs",      desc: "Angle: montrer ma propre routine. Utiliser des timestamps. Format long ~15min.", plt: "youtube",   type: "Vidéo",     prio: "high", date: "2026-05-12", tags: ["productivité", "routine", "tips"],         views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c2",  col: "ideas", title: "Mon setup créatif 2026 — tour complet",             desc: "Filmer le bureau entier, tous les équipements, logiciels, workflow.",         plt: "youtube",   type: "Vidéo",     prio: "med",  date: "",           tags: ["setup", "gear", "workspace"],               views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c3",  col: "ideas", title: "Carrousel: Notion pour créateurs de contenu",        desc: "Template Notion que j'utilise quotidiennement. Angle pratique.",              plt: "instagram", type: "Carrousel", prio: "low",  date: "",           tags: ["notion", "organisation"],                   views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c4",  col: "ideas", title: "Thread: mes 5 sources d'inspiration créative",      desc: "",                                                                           plt: "twitter",   type: "Thread",    prio: "low",  date: "",           tags: ["inspiration", "créativité"],                views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c5",  col: "plan",  title: "Comment l'IA transforme la création de contenu",    desc: "Rechercher des stats récentes, exemples concrets, angle: créateur + IA = super-créateur.", plt: "youtube",   type: "Vidéo",     prio: "high", date: "2026-05-05", tags: ["IA", "tendances", "futur"],                 views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c6",  col: "plan",  title: "Thread: 7 erreurs à éviter en tant que créateur débutant", desc: "Erreurs que j'ai faites moi-même. Ton authentique et direct.",       plt: "twitter",   type: "Thread",    prio: "med",  date: "2026-04-30", tags: ["débutants", "erreurs", "apprentissage"],    views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c7",  col: "prod",  title: "Vlog: une semaine de tournage intensif",            desc: "Coulisses de la production de 5 vidéos en 7 jours. Format journalier.",      plt: "youtube",   type: "Vidéo",     prio: "high", date: "2026-04-27", tags: ["vlog", "bts", "processus"],                 views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c8",  col: "edit",  title: "Top outils no-code pour créateurs — réaction & review", desc: "Montage à 65%, il reste intro, musique et sous-titres auto.",           plt: "youtube",   type: "Vidéo",     prio: "high", date: "2026-04-25", tags: ["no-code", "outils", "review"],              views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c9",  col: "sched", title: "Reel: ma routine matinale en 60 secondes",          desc: "Publié vendredi 26 avril à 8h. Musique tendance ajoutée.",                   plt: "instagram", type: "Reel",      prio: "med",  date: "2026-04-26", tags: ["routine", "matinale", "lifestyle"],         views: 0,     likes: 0,    learning: "", prodNotes: "" },
  { id: "c10", col: "pub",   title: "Comment j'ai gagné 1000 abonnés en 30 jours",       desc: "Stratégie complète, honnête et transparente sur ma croissance organique.",    plt: "youtube",   type: "Vidéo",     prio: "high", date: "2026-04-15", tags: ["croissance", "stratégie", "abonnés"],       views: 12400, likes: 843,  learning: "Le titre avec chiffre concret + délai précis cartonne. Refaire ce format.", prodNotes: "Filmé en 3h, monté 4h sur Premiere. Script écrit 2 jours avant." },
  { id: "c11", col: "pub",   title: "Carrousel: 5 apps gratuites pour créer du contenu", desc: "Top 5 apps mobiles accessibles à tous les créateurs débutants.",             plt: "instagram", type: "Carrousel", prio: "med",  date: "2026-04-18", tags: ["apps", "gratuit", "outils"],                views: 4200,  likes: 389,  learning: "Bon engagement. Le format \"liste numérotée\" fonctionne toujours bien sur IG.", prodNotes: "Créé sur Canva en 45min. 5 slides + cover." },
  { id: "c12", col: "arch",  title: "Pourquoi j'ai failli tout arrêter (burnout créatif)", desc: "Vidéo très personnelle. Format confession. A très bien marché côté rétention.", plt: "youtube",   type: "Vidéo",     prio: "med",  date: "2026-02-10", tags: ["burnout", "personnel", "authenticité"],     views: 34500, likes: 2100, learning: "L'authenticité surpasse le polissage. Vidéo peu montée, beaucoup de commentaires émotionnels. À refaire.", prodNotes: "Tourné en une prise, selfie cam. Pas de script. 18 minutes brutes." },
  { id: "c13", col: "arch",  title: "Podcast ep.12 — Interview créateur invité",         desc: "Épisode le plus long (1h20). Format conversationnel naturel.",               plt: "podcast",   type: "Épisode",   prio: "low",  date: "2026-01-22", tags: ["interview", "invité", "créateurs"],         views: 1800,  likes: 95,   learning: "Format interview > solo pour l'engagement. Inviter 1 créateur par mois.", prodNotes: "Enregistré sur Riverside.fm. Montage audio : 2h sur Audacity." },
];
